vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    mappings:
        Article:
            uri_prefix:         /images/article
            upload_destination: '%kernel.project_dir%/public/images/article'
        #category_images:
        #    uri_prefix:         '%app.path.category_images%'
        #    upload_destination: '%kernel.project_dir%/public%app.path.#category_images%' 
            #inject_on_load: true
            #delete_on_update: true
            #delete_on_remove: true
            inject_on_load: true
            delete_on_update: false
            delete_on_remove: true